name: routelog_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 앱 재실행 후에도 테마(라이트/다크/시스템) 유지
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  path_provider: ^2.1.5

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

